#' plotCorrMatrix
#'
#' This function generates a plot of a correlation matrix with various options. It is a wrapper function for
#' the corrplot function from the {corrplot} package.
#' @param x a correlation matrix, typically generated by a call to calcCorrMatrix or the base fn cov()
#' @param order either "original" or "clustered" (for now, other options to be explored)
#' @param order
#' @param zero.convert replace 0 with this value if required by the transformation (e.g. log)
#' @keywords transform, z-score, percent rank
#' @export
#' @examples
#' iris.transform <- transformData(iris,
#'    type="log",
#'    cols="Sepal.Length",
#'    zero.convert = NA)
#' head(iris.transform)




type <-

# do not display values in the principal diagonal
diag <- FALSE

corrplot(X, type= "upper",diag = FALSE, method = "circle",
         order = "original",mar = c(2, 2, 2, 2))

title(main= "Basic Correlation Matrix",line=3)

corrplot(cor.mat.basic, order = "hclust", addrect = round(dim(cor.mat.basic)[1]/3),
         diag = FALSE,   mar = c(2, 2, 2, 2))




